import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { requestSpeedRiskAdvisory } from '../services/api'
import type { SpeedRiskAdvisoryResponse, SpeedRiskAdvisoryRequest } from '../types/speed'

function isoNow(): string {
  return new Date().toISOString()
}

function source(key: string, type: 'AUTHORIZED_FEED' | 'IMPORTED_DOCUMENT', reference: string, checksum: string, observedAt: string, validUntil: string) {
  return {
    source_key: key,
    source_type: type,
    authority_level: 'AUTHORITATIVE' as const,
    source_reference: reference,
    observed_at: observedAt.trim(),
    // The API request time is the fetch time for this user-supplied evidence
    // envelope; the observation and validity timestamps must be copied from
    // the real source rather than generated by the browser.
    fetched_at: isoNow(),
    valid_until: validUntil.trim(),
    checksum,
  }
}

/**
 * Human-review panel for the read-only speed advisory. It intentionally has
 * no speed defaults: operators must enter values from real authorized
 * railway evidence and a real consist brake document.
 */
export default function SpeedRiskAdvisoryPanel() {
  const [corridorReference, setCorridorReference] = useState('')
  const [consistChecksum, setConsistChecksum] = useState('')
  const [observedAt, setObservedAt] = useState('')
  const [validUntil, setValidUntil] = useState('')
  const [routeLimit, setRouteLimit] = useState('')
  const [headwayLimit, setHeadwayLimit] = useState('')
  const [routeSource, setRouteSource] = useState('')
  const [headwaySource, setHeadwaySource] = useState('')
  const [routeChecksum, setRouteChecksum] = useState('')
  const [headwayChecksum, setHeadwayChecksum] = useState('')
  const [brakeSource, setBrakeSource] = useState('')
  const [brakeChecksum, setBrakeChecksum] = useState('')
  const [deceleration, setDeceleration] = useState('')
  const [reaction, setReaction] = useState('')
  const [margin, setMargin] = useState('')
  const [result, setResult] = useState<SpeedRiskAdvisoryResponse | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)

  const disabled = useMemo(
    () => loading || !corridorReference.trim() || !consistChecksum.trim() || !observedAt.trim() || !validUntil.trim() || !routeLimit || !headwayLimit || !routeSource.trim() || !routeChecksum.trim() || !headwaySource.trim() || !headwayChecksum.trim() || !brakeSource.trim() || !brakeChecksum.trim() || !deceleration || !reaction || !margin,
    [loading, corridorReference, consistChecksum, observedAt, validUntil, routeLimit, headwayLimit, routeSource, routeChecksum, headwaySource, headwayChecksum, brakeSource, brakeChecksum, deceleration, reaction, margin],
  )

  async function submit(event: FormEvent) {
    event.preventDefault()
    setLoading(true)
    setError(null)
    setResult(null)
    const evaluatedAt = isoNow()
    const payload: SpeedRiskAdvisoryRequest = {
      corridor_reference: corridorReference.trim(),
      consist_manifest_checksum: consistChecksum.trim(),
      evaluation_at: evaluatedAt,
      constraints: [
        {
          category: 'ROUTE_LIMIT',
          label: 'Authorized route speed limit',
          limit_kph: Number(routeLimit),
          evidence: source('route_speed_limit', 'AUTHORIZED_FEED', routeSource.trim(), routeChecksum.trim(), observedAt, validUntil),
        },
        {
          category: 'HEADWAY',
          label: 'Authorized block/headway cap',
          limit_kph: Number(headwayLimit),
          evidence: source('block_headway', 'AUTHORIZED_FEED', headwaySource.trim(), headwayChecksum.trim(), observedAt, validUntil),
        },
      ],
      braking: {
        effective_deceleration_mps2: Number(deceleration),
        reaction_time_seconds: Number(reaction),
        safety_margin_meters: Number(margin),
        evidence: source('consist_brake_test', 'IMPORTED_DOCUMENT', brakeSource.trim(), brakeChecksum.trim(), observedAt, validUntil),
      },
    }
    try {
      setResult(await requestSpeedRiskAdvisory(payload))
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : 'The advisory request failed closed.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 shadow-xl" aria-labelledby="speed-advisory-title">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-400">Evidence-backed advisory</p>
          <h2 id="speed-advisory-title" className="mt-1 text-xl font-bold text-slate-100">Speed &amp; headway risk</h2>
          <p className="mt-1 max-w-2xl text-xs leading-5 text-slate-400">
            Enter values copied from current authorized sources and the actual consist brake record. There are no default speed values; missing or expired evidence produces no number.
          </p>
        </div>
        <span className="rounded-full border border-amber-400/40 bg-amber-400/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-amber-200">Advisory only</span>
      </div>

      <form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2">
        <label className="text-xs text-slate-400">Corridor or authority reference<input required value={corridorReference} onChange={(event) => setCorridorReference(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" placeholder="e.g. authority corridor ID" /></label>
        <label className="text-xs text-slate-400">Actual consist manifest SHA-256<input required pattern="[A-Fa-f0-9]{64}" value={consistChecksum} onChange={(event) => setConsistChecksum(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="64 hexadecimal characters" /></label>
        <label className="text-xs text-slate-400">Source observed at (timezone-aware ISO-8601)<input required value={observedAt} onChange={(event) => setObservedAt(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="Copy from the real feed, e.g. 2026-09-14T10:00:00Z" /></label>
        <label className="text-xs text-slate-400">Source valid until (timezone-aware ISO-8601)<input required value={validUntil} onChange={(event) => setValidUntil(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="Copy the source validity window" /></label>
        <label className="text-xs text-slate-400">Authorized route-limit source URL/ID<input required value={routeSource} onChange={(event) => setRouteSource(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" placeholder="Paste the real source reference" /></label>
        <label className="text-xs text-slate-400">Route speed limit (km/h)<input required type="number" min="0.1" step="0.1" value={routeLimit} onChange={(event) => setRouteLimit(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label>
        <label className="text-xs text-slate-400">Route-limit payload SHA-256<input required pattern="[A-Fa-f0-9]{64}" value={routeChecksum} onChange={(event) => setRouteChecksum(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="64 hexadecimal characters" /></label>
        <label className="text-xs text-slate-400">Authorized block/headway source URL/ID<input required value={headwaySource} onChange={(event) => setHeadwaySource(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" placeholder="Paste the real source reference" /></label>
        <label className="text-xs text-slate-400">Headway/block cap (km/h)<input required type="number" min="0.1" step="0.1" value={headwayLimit} onChange={(event) => setHeadwayLimit(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label>
        <label className="text-xs text-slate-400">Headway payload SHA-256<input required pattern="[A-Fa-f0-9]{64}" value={headwayChecksum} onChange={(event) => setHeadwayChecksum(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="64 hexadecimal characters" /></label>
        <label className="text-xs text-slate-400">Brake-test document URL/ID<input required value={brakeSource} onChange={(event) => setBrakeSource(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" placeholder="Real consist document reference" /></label>
        <label className="text-xs text-slate-400">Effective deceleration (m/s²)<input required type="number" min="0.01" step="0.01" value={deceleration} onChange={(event) => setDeceleration(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label>
        <label className="text-xs text-slate-400">Brake document SHA-256<input required pattern="[A-Fa-f0-9]{64}" value={brakeChecksum} onChange={(event) => setBrakeChecksum(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100" placeholder="64 hexadecimal characters" /></label>
        <label className="text-xs text-slate-400">Driver/consist reaction interval (s)<input required type="number" min="0.01" step="0.01" value={reaction} onChange={(event) => setReaction(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label>
        <label className="text-xs text-slate-400">Documented safety margin (m)<input required type="number" min="0" step="0.1" value={margin} onChange={(event) => setMargin(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100" /></label>
        <div className="md:col-span-2 flex flex-wrap items-center gap-3">
          <button type="submit" disabled={disabled} className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{loading ? 'Checking evidence…' : 'Calculate advisory'}</button>
          <span className="text-[11px] text-slate-500">Only the evaluation/fetch time is generated at request time; provider values, checksums, observation time, and validity must come from real evidence.</span>
        </div>
      </form>

      {error && <p role="alert" className="mt-4 rounded-lg border border-rose-400/30 bg-rose-400/10 p-3 text-xs text-rose-200">{error}</p>}
      {result && (
        <div className="mt-5 space-y-4 border-t border-slate-800 pt-4">
          <div className="flex flex-wrap items-end gap-5">
            <div><p className="text-[10px] uppercase tracking-wide text-slate-500">Status</p><p className="text-lg font-bold text-cyan-300">{result.status}</p></div>
            <div><p className="text-[10px] uppercase tracking-wide text-slate-500">Advisory maximum</p><p className="text-lg font-bold text-slate-100">{result.advisory_speed_kph == null ? 'Unavailable' : `${result.advisory_speed_kph} km/h`}</p></div>
            <div><p className="text-[10px] uppercase tracking-wide text-slate-500">Stopping estimate</p><p className="text-lg font-bold text-slate-100">{result.stopping_distance_meters == null ? 'Unavailable' : `${result.stopping_distance_meters} m`}</p></div>
            {result.limiting_constraint && <div><p className="text-[10px] uppercase tracking-wide text-slate-500">Limiting evidence</p><p className="text-sm font-semibold text-slate-200">{result.limiting_constraint}</p></div>}
          </div>
          {result.warnings.length > 0 && <ul className="space-y-1 text-xs text-amber-200">{result.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul>}
          <div className="overflow-x-auto"><table className="w-full text-left text-[11px]"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="p-2">Input</th><th className="p-2">Source</th><th className="p-2">Freshness</th><th className="p-2">Decision use</th></tr></thead><tbody>{result.evidence.map((item) => <tr key={`${item.category}-${item.source_key}`} className="border-b border-slate-800/70"><td className="p-2 text-slate-300">{item.label}</td><td className="p-2 font-mono text-cyan-300">{item.source_key}</td><td className="p-2 text-slate-400">{item.freshness}</td><td className="p-2">{item.used_in_decision ? <span className="text-emerald-300">Used</span> : <span className="text-amber-300">Excluded: {item.excluded_reason}</span>}</td></tr>)}</tbody></table></div>
          <p className="text-[11px] leading-5 text-slate-500">{result.disclaimer}</p>
        </div>
      )}
    </section>
  )
}
